name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Only needed for non-self-hosted
      # - name: Setup bun
      #   uses: oven-sh/setup-bun@v2
      #   with:
      #     bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Deploy
        run: make deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
